apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backstage.yaml
  - app-config.yaml
  - dynamic-plugins.yaml
  - rhdh-rbac-policy.yaml
  - rcsconfig.yaml

namespace: developer-hub
